apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: developer-cluster-1
  annotations:
    kubernetes.io/api-server: 'https://10.16.0.129:6443'
    kubernetes.io/auth-provider: 'localKubectlProxy'
spec:
  type: kubernetes-cluster
  owner: guest